version: '2'
services:
  db:
    image: postgres
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
  new-trello:
    build: .
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/new-trello
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=
    depends_on:
      - db